vim.keymap.set("n", "<leader>dr", function() require('dap.repl').toggle({ height = 10 }) end )
vim.keymap.set("n", "<leader>db", function() require('dap').toggle_breakpoint() end )
vim.keymap.set("n", "<leader>dsc", function() require('dap').continue() end )
vim.keymap.set("n", "<leader>dst", function() require('dap').terminate() end )
vim.keymap.set("n", "<leader>dsi", function() require('dap').step_into() end )
vim.keymap.set("n", "<leader>dso", function() require('dap').step_out() end )
vim.keymap.set("n", "<leader>dsv", function() require('dap').step_over() end )
